### ISSUE TITLE
enumerate_paths

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Graphs.jl#166]
Hello,

I had some simple code that just called dijkstra and printed the shortest path from a specific node.
It looked like this:

```julia
path_state = dijkstra_shortest_paths(inc_list, dists, start_node)
println("Shortest path: ", enumerate_paths(path_state, end_node))
```
which worked fine. I now updated my packages for Julia and get the following error with the same code:

```julia
ERROR: `enumerate_paths` has no method matching enumerate_paths(::DijkstraStates
{Int64,Float64,MutableBinaryHeap{DijkstraHEntry{Int64,Float64},LessThan},Int64},
 ::Int64)
```

Now, I instead have to call `enumerate_paths` like this:

```julia
println("Shortest path: ", enumerate_paths(vertices(inc_list), path_state.parent_indices,  end_node))
```

It was kinda smooth to just pass in the path_state to `enumerate_paths`.

Is there a reason this changed?

**Comment by mlubin** [comment]
CC @sbromberger @yeesian

**Comment by sbromberger** [comment]
IIUC,  vertices are required for enumerate_paths now because of #150 and, in general, because Graphs.jl vertices are not guaranteed to be ordered or even Number, and because the `parent` attribute of `DijkstraStates` returns the actual parent, not the `vertex_index`.

**Comment by yeesian** [comment]
I'm sorry about the breaking change, and also prefer the previous version of `enumerate_paths` too. Unfortunately, the `path_state::DijkstraState` you speak of doesn't encode sufficient information to print out the paths for a general graph: here's [an example where it fails](https://github.com/JuliaLang/Graphs.jl/issues/150#issuecomment-70024640). I've tried, but failed to implement a simpler (and efficient) interface for reasons @sbromberger has mentioned.

The situation now might be different with [recent changes](https://github.com/JuliaLang/Graphs.jl/issues/160) -- but I think these are just symptoms of a more [general observation](https://github.com/JuliaLang/Graphs.jl/issues/160#issuecomment-71106182) that this package might be "a little too general to be useful" (since it's trying to provide *both* (i) generic graph interfaces, and (ii) specific implementations*) -- hopefully something fruitful might emerge from https://github.com/JuliaLang/Graphs.jl/issues/165.

**Comment by KristofferC** [comment]
Well, if the information is not in the Dijkstra state there anymore then you just have to call it with both arguments :)

Thanks for the information!
